/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.19.6
 * source: chat.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export namespace chat {
    export enum MessageType {
        TEXT = 0,
        PHOTO = 1
    }
    export class ChatMessage extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            type?: MessageType;
            content?: string;
            user_id?: string;
            timestamp?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("type" in data && data.type != undefined) {
                    this.type = data.type;
                }
                if ("content" in data && data.content != undefined) {
                    this.content = data.content;
                }
                if ("user_id" in data && data.user_id != undefined) {
                    this.user_id = data.user_id;
                }
                if ("timestamp" in data && data.timestamp != undefined) {
                    this.timestamp = data.timestamp;
                }
            }
        }
        get type() {
            return pb_1.Message.getFieldWithDefault(this, 1, MessageType.TEXT) as MessageType;
        }
        set type(value: MessageType) {
            pb_1.Message.setField(this, 1, value);
        }
        get content() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set content(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get user_id() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set user_id(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get timestamp() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set timestamp(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        static fromObject(data: {
            type?: MessageType;
            content?: string;
            user_id?: string;
            timestamp?: number;
        }): ChatMessage {
            const message = new ChatMessage({});
            if (data.type != null) {
                message.type = data.type;
            }
            if (data.content != null) {
                message.content = data.content;
            }
            if (data.user_id != null) {
                message.user_id = data.user_id;
            }
            if (data.timestamp != null) {
                message.timestamp = data.timestamp;
            }
            return message;
        }
        toObject() {
            const data: {
                type?: MessageType;
                content?: string;
                user_id?: string;
                timestamp?: number;
            } = {};
            if (this.type != null) {
                data.type = this.type;
            }
            if (this.content != null) {
                data.content = this.content;
            }
            if (this.user_id != null) {
                data.user_id = this.user_id;
            }
            if (this.timestamp != null) {
                data.timestamp = this.timestamp;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.type != MessageType.TEXT)
                writer.writeEnum(1, this.type);
            if (this.content.length)
                writer.writeString(2, this.content);
            if (this.user_id.length)
                writer.writeString(3, this.user_id);
            if (this.timestamp != 0)
                writer.writeInt64(4, this.timestamp);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ChatMessage {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ChatMessage();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.type = reader.readEnum();
                        break;
                    case 2:
                        message.content = reader.readString();
                        break;
                    case 3:
                        message.user_id = reader.readString();
                        break;
                    case 4:
                        message.timestamp = reader.readInt64();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ChatMessage {
            return ChatMessage.deserialize(bytes);
        }
    }
    export class AddChatRoomRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            participant?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("participant" in data && data.participant != undefined) {
                    this.participant = data.participant;
                }
            }
        }
        get participant() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set participant(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            participant?: string;
        }): AddChatRoomRequest {
            const message = new AddChatRoomRequest({});
            if (data.participant != null) {
                message.participant = data.participant;
            }
            return message;
        }
        toObject() {
            const data: {
                participant?: string;
            } = {};
            if (this.participant != null) {
                data.participant = this.participant;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.participant.length)
                writer.writeString(1, this.participant);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): AddChatRoomRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new AddChatRoomRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.participant = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): AddChatRoomRequest {
            return AddChatRoomRequest.deserialize(bytes);
        }
    }
    export class ChatRoom extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            id?: number;
            userId?: string;
            name?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("id" in data && data.id != undefined) {
                    this.id = data.id;
                }
                if ("userId" in data && data.userId != undefined) {
                    this.userId = data.userId;
                }
                if ("name" in data && data.name != undefined) {
                    this.name = data.name;
                }
            }
        }
        get id() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set id(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get userId() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set userId(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get name() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set name(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        static fromObject(data: {
            id?: number;
            userId?: string;
            name?: string;
        }): ChatRoom {
            const message = new ChatRoom({});
            if (data.id != null) {
                message.id = data.id;
            }
            if (data.userId != null) {
                message.userId = data.userId;
            }
            if (data.name != null) {
                message.name = data.name;
            }
            return message;
        }
        toObject() {
            const data: {
                id?: number;
                userId?: string;
                name?: string;
            } = {};
            if (this.id != null) {
                data.id = this.id;
            }
            if (this.userId != null) {
                data.userId = this.userId;
            }
            if (this.name != null) {
                data.name = this.name;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.id != 0)
                writer.writeInt64(1, this.id);
            if (this.userId.length)
                writer.writeString(2, this.userId);
            if (this.name.length)
                writer.writeString(3, this.name);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ChatRoom {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ChatRoom();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.id = reader.readInt64();
                        break;
                    case 2:
                        message.userId = reader.readString();
                        break;
                    case 3:
                        message.name = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ChatRoom {
            return ChatRoom.deserialize(bytes);
        }
    }
    export class ChatRoomList extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            rooms?: ChatRoom[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("rooms" in data && data.rooms != undefined) {
                    this.rooms = data.rooms;
                }
            }
        }
        get rooms() {
            return pb_1.Message.getRepeatedWrapperField(this, ChatRoom, 1) as ChatRoom[];
        }
        set rooms(value: ChatRoom[]) {
            pb_1.Message.setRepeatedWrapperField(this, 1, value);
        }
        static fromObject(data: {
            rooms?: ReturnType<typeof ChatRoom.prototype.toObject>[];
        }): ChatRoomList {
            const message = new ChatRoomList({});
            if (data.rooms != null) {
                message.rooms = data.rooms.map(item => ChatRoom.fromObject(item));
            }
            return message;
        }
        toObject() {
            const data: {
                rooms?: ReturnType<typeof ChatRoom.prototype.toObject>[];
            } = {};
            if (this.rooms != null) {
                data.rooms = this.rooms.map((item: ChatRoom) => item.toObject());
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.rooms.length)
                writer.writeRepeatedMessage(1, this.rooms, (item: ChatRoom) => item.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ChatRoomList {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ChatRoomList();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.rooms, () => pb_1.Message.addToRepeatedWrapperField(message, 1, ChatRoom.deserialize(reader), ChatRoom));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ChatRoomList {
            return ChatRoomList.deserialize(bytes);
        }
    }
    export class MessageModel extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            id?: string;
            SenderId?: string;
            RoomId?: string;
            text?: string;
            CreatedAt?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("id" in data && data.id != undefined) {
                    this.id = data.id;
                }
                if ("SenderId" in data && data.SenderId != undefined) {
                    this.SenderId = data.SenderId;
                }
                if ("RoomId" in data && data.RoomId != undefined) {
                    this.RoomId = data.RoomId;
                }
                if ("text" in data && data.text != undefined) {
                    this.text = data.text;
                }
                if ("CreatedAt" in data && data.CreatedAt != undefined) {
                    this.CreatedAt = data.CreatedAt;
                }
            }
        }
        get id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get SenderId() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set SenderId(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get RoomId() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set RoomId(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get text() {
            return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
        }
        set text(value: string) {
            pb_1.Message.setField(this, 4, value);
        }
        get CreatedAt() {
            return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
        }
        set CreatedAt(value: number) {
            pb_1.Message.setField(this, 5, value);
        }
        static fromObject(data: {
            id?: string;
            SenderId?: string;
            RoomId?: string;
            text?: string;
            CreatedAt?: number;
        }): MessageModel {
            const message = new MessageModel({});
            if (data.id != null) {
                message.id = data.id;
            }
            if (data.SenderId != null) {
                message.SenderId = data.SenderId;
            }
            if (data.RoomId != null) {
                message.RoomId = data.RoomId;
            }
            if (data.text != null) {
                message.text = data.text;
            }
            if (data.CreatedAt != null) {
                message.CreatedAt = data.CreatedAt;
            }
            return message;
        }
        toObject() {
            const data: {
                id?: string;
                SenderId?: string;
                RoomId?: string;
                text?: string;
                CreatedAt?: number;
            } = {};
            if (this.id != null) {
                data.id = this.id;
            }
            if (this.SenderId != null) {
                data.SenderId = this.SenderId;
            }
            if (this.RoomId != null) {
                data.RoomId = this.RoomId;
            }
            if (this.text != null) {
                data.text = this.text;
            }
            if (this.CreatedAt != null) {
                data.CreatedAt = this.CreatedAt;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.id.length)
                writer.writeString(1, this.id);
            if (this.SenderId.length)
                writer.writeString(2, this.SenderId);
            if (this.RoomId.length)
                writer.writeString(3, this.RoomId);
            if (this.text.length)
                writer.writeString(4, this.text);
            if (this.CreatedAt != 0)
                writer.writeInt64(5, this.CreatedAt);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MessageModel {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MessageModel();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.id = reader.readString();
                        break;
                    case 2:
                        message.SenderId = reader.readString();
                        break;
                    case 3:
                        message.RoomId = reader.readString();
                        break;
                    case 4:
                        message.text = reader.readString();
                        break;
                    case 5:
                        message.CreatedAt = reader.readInt64();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MessageModel {
            return MessageModel.deserialize(bytes);
        }
    }
    export class MessageModelList extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            messages?: MessageModel[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("messages" in data && data.messages != undefined) {
                    this.messages = data.messages;
                }
            }
        }
        get messages() {
            return pb_1.Message.getRepeatedWrapperField(this, MessageModel, 1) as MessageModel[];
        }
        set messages(value: MessageModel[]) {
            pb_1.Message.setRepeatedWrapperField(this, 1, value);
        }
        static fromObject(data: {
            messages?: ReturnType<typeof MessageModel.prototype.toObject>[];
        }): MessageModelList {
            const message = new MessageModelList({});
            if (data.messages != null) {
                message.messages = data.messages.map(item => MessageModel.fromObject(item));
            }
            return message;
        }
        toObject() {
            const data: {
                messages?: ReturnType<typeof MessageModel.prototype.toObject>[];
            } = {};
            if (this.messages != null) {
                data.messages = this.messages.map((item: MessageModel) => item.toObject());
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.messages.length)
                writer.writeRepeatedMessage(1, this.messages, (item: MessageModel) => item.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MessageModelList {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MessageModelList();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.messages, () => pb_1.Message.addToRepeatedWrapperField(message, 1, MessageModel.deserialize(reader), MessageModel));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MessageModelList {
            return MessageModelList.deserialize(bytes);
        }
    }
}
